title: New things I learnt (by Zyrouge)
description: Documenting everything I newly learn.
remote_theme: jekyll/minima
author:
    name: Zyrouge
    email: "zyrouge@hotmail.com"
minima:
    skin: auto
    social_links:
        - platform: github
          user_url: "https://github.com/zyrouge/new-things-i-learnt"
header_pages:
    -
plugins:
    - jekyll-titles-from-headings
titles_from_headings:
    enabled: true
    strip_title: true
    collections: true
